module.exports = {
    REGISTER_TITLE: 'div[class="container center"] > h2',
    FIRST_NAME: 'input[placeholder="First Name"]',
    LAST_NAME: 'input[placeholder="Last Name"]',
    ADDRESS: '.form-group > div > textarea',
    EMAIL_ADDRESS: 'input[type="email"]',
    PHONE: '#basicBootstrapForm > div:nth-child(4) > div > input',
    GENDER_MALE: '.form-group:nth-child(5) > div > label:nth-child(1)',
    GENDER_FEMALE:  '.form-group:nth-child(5) > div > label:nth-child(2)',
    HOBBIES: `#checkbox`,
    SELECT_LANGUAGE: '[class*="ui-menu"]',
    LANGUAGES: 'ul[class*="ui-menu"]',
    SKILLS: '#Skills',
    SELECT_COUNTRY: '.selection:nth-child(1) > span',
    INPUT_COUNTRY: 'span[class*="below"] span input',
    SELECT_NETHERLANDS: '#select2-country-results li:first-child',  
    DAY_OF_BIRTH: '#daybox',
    MONTH_OF_BIRTH: '[placeholder="Month"]',
    YEAR_OF_BIRTH: '#yearbox',
    PASSWORD: '#firstpassword',
    CONFIRM_PASSWORD: '#secondpassword',
    BTN_SUBMIT: '#submitbtn',
    BTN_REFRESH: '#Button1'
}